spring.application.name=assets

logging.level.root=info
logging.level.com.investment.assets=debug
logging.level.org.springframework.web=debug
logging.level.org.springframework.jdbc=debug


# Application
app.access-key=${UPBIT_ACCESS_KEY}
app.secret-key=${UPBIT_SECRET_KEY}