spring:
  application:
    name: assets
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  Kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: info
    com.investment.assets: debug
    org.springframework.web: debug
    org.springframework.jdbc: debug

upbit:
  access-key: ${UPBIT_ACCESS_KEY}
  secret-key: ${UPBIT_SECRET_KEY}
  #OCI docker 내부망 ip
  proxy-url: ${PROXY_SERVER:http://158.180.83.196}