package com.investment.assets.upbit.dto;

public record Ticker (
    String market,
    String trade_date,
    String trade_time,
    String trade_date_kst,
    String trade_time_kst,
    long trade_timestamp,
    String opening_price,
    String high_price,
    String low_price,
    String trade_price,
    String prev_closing_price,
    String change,
    long change_price,
    double change_rate,
    String signed_change_price,
    String signed_change_rate,
    String trade_volume,
    double acc_trade_price,
    double acc_trade_price_24h,
    double acc_trade_volume,
    double acc_trade_volume_24h,
    long highest_52_week_price,
    String highest_52_week_date,
    long lowest_52_week_price,
    String lowest_52_week_date,
    long timestamp
){}
