spring.application.name=assets

logging.level.root=info
logging.level.com.investment.assets=debug
logging.level.org.springframework.web=debug
logging.level.org.springframework.jdbc=debug


# Application
app.access-key=oA8y1RjUSPETrnhS8ry1FkRjwfXq1njm9Lviq3Sg
app.secret-key=ZaJxcqfPEC7JsgpXqIQf5TaZrAp5NjDx7eQS2Iav